elasticsearch:
  setting:
    host: localhost
    port: 9200
application:
  demo: false
spring:
  thymeleaf:
    enable-spring-el-compiler: true
    encoding: UTF-8
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3360/freitech
    username: freitech
    password: ft_033
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
  # これ書いてないと既存のDB使う場合はbaselineほげで怒られる
  flyway:
    baseline-description: Initial
    baseline-version: 1
    baseline-on-migrate: true
